os: linux
arch:
  - amd64
  - arm64
sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
matrix:
  include:
    - language: generic
      os: osx
      install: pip2 install tox-travis
      script: tox --skip-missing-interpreters
  allow_failures:
    - os: osx
install: pip install tox-travis
script: tox
